#!/bin/sh

#just launches GATK selectVariants

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S656/MERGED_SAMPLES/2395/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S656/SU1768/7467/SU1768.vcf -sn SU1768

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S656/MERGED_SAMPLES/2395/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S656/SU1788/7467/SU1788.vcf -sn SU1788

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S656/MERGED_SAMPLES/2395/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S656/SU3574/7467/SU3574.vcf -sn SU3574

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1640/MERGED_SAMPLES/29817/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1640/SU4288/19368/SU4288.vcf -sn SU4288

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1640/MERGED_SAMPLES/29817/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1640/SU4289/19368/SU4289.vcf -sn SU4289

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1640/MERGED_SAMPLES/29817/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1640/SU4290/19368/SU4290.vcf -sn SU4290

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1731/MERGED_SAMPLES/9568/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1731/SU4479/18160/SU4479.vcf -sn SU4479

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1731/MERGED_SAMPLES/9568/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1731/SU4480/18160/SU4480.vcf -sn SU4480

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1731/MERGED_SAMPLES/9568/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/S1731/SU4481/18160/SU4481.vcf -sn SU4481

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/U1525/MERGED_SAMPLES/15466/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/U1525/SU4006/27575/SU4006.vcf -sn SU4006

srun --job-name=srun_split -N1 -n1 -c24 --partition=monster --account=IURC /usr/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ /home/neuro_admin/nenufaar/software/GenomeAnalysisTK/3.6.0/GenomeAnalysisTK.jar -T SelectVariants -R /home/neuro_admin/nenufaar/refData/genome/hg19/hg19.fa -nt 24 --variant /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/U1525/MERGED_SAMPLES/15466/MERGED_SAMPLES.final.vcf -o /RS_IURC/data/MiSeqDx/USHER/truesight_nenufaar/U1525/SU4007/27575/SU4007.vcf -sn SU4007



#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant ../../output/MYO/MERGED_SAMPLES.final.vcf -o ../../output/MYO/I362.vcf -sn I362

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmpjp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant ../../output/MYO/MERGED_SAMPLES.final.vcf -o ../../output/MYO/I91.vcf -sn I91

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant ../../output/21053/family_JUL/MERGED_SAMPLES/27748/MERGED_SAMPLES.final.vcf -o i6.vcf -sn i6

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant ../../output/21053/family_JUL/MERGED_SAMPLES/27748/MERGED_SAMPLES.final.vcf -o i7.vcf -sn i7

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant ../../output/21053/family_JUL/MERGED_SAMPLES/27748/MERGED_SAMPLES.final.vcf -o i8.vcf -sn i8

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant ../../output/8757/family_ICH/MERGED_SAMPLES/4508/MERGED_SAMPLES.final.vcf -o B00HKLL2.vcf -sn B00HKLL2

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant MERGED_SAMPLES.final.vcf -o B00HLK8.vcf -sn B00HLK8

#srun --job-name=srun_split -N1 -n1 -c24 --partition=defq --account=IURC /gpfs2/cluster/softs/jdk-1.8.25/jdk1.8.0_25/bin/java -jar -Xmx48g -Djava.io.tmpdir=tmp/ ../../software/GenomeAnalysisTK/3.5.0/GenomeAnalysisTK.jar -T SelectVariants -R ../../refData/genome/hg19/hg19.fa -nt 24 --variant MERGED_SAMPLES.final.vcf -o B00HLK9.vcf -sn B00HLK9